name: First attempt
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: dummystep
        run: echo "Hello World!" 

      - name: checokout code
        uses: actions/checkout@v2
      
      - name: SetUp node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: testing
        run: npm test

